baseURL = "https://www.yooripark.com/"
languageCode = "en-us"
summaryLength = 20
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Sold Properties"
parent = "Properties"
url = "/status/sold/"
weight = 2
[[menu.main]]
name = "Exclusive Properties"
parent = "Properties"
url = "/featured/featured/"
weight = 1
[[menu.main]]
name = "Services"
weight = 4
[[menu.main]]
name = "Properties"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
cloudinary_url = "https://res.cloudinary.com/realestate2/image/upload/"
[taxonomies]
category = "categories"
city = "cities"
featured = "featured"
property = "properties"
state = "states"
status = "status"
tag = "tags"
zip = "zip-codes"
