baseURL = "https://yoori2021.netlify.app/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Sold Properties"
parent = "Properties"
url = "/status/sold/"
weight = 2
[[menu.main]]
name = "Exclusive Properties"
parent = "Properties"
url = "/featured/featured/"
weight = 1
[[menu.main]]
name = "Services"
weight = 4
[[menu.main]]
name = "Properties"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"