baseURL = "https://www.yooripark.com/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
