baseURL = "https://www.yooripark.com/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
<<<<<<< HEAD
=======
[[menu.footer]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Properties"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Exclusive Properties"
parent = "Properties"
url = "/featured/featured/"
weight = 1
[[menu.main]]
name = "Sold Properties"
parent = "Properties"
url = "/status/sold/"
weight = 2
[[menu.main]]
name = "Buyers & Sellers"
weight = 4
>>>>>>> e8819b6f0b73c748110212b54bb5619b059a2ea8
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
