baseURL = "https://www.yooripark.com/"
enableRobotsTXT = "true"
languageCode = "en-us"
summaryLength = 25
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
weight = 4
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
cities = "cities"
featured = "featured"
properties = "properties"
states = "states"
status = "status"
tag = "tags"
