---
label: Services
hide_body: true
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: image
  type: file
  config:
    maxSize: 2
  label: Image
- name: image_alt_tag
  type: text
  config:
    required: false
  label: Image Alt Tag
- name: heading
  type: text
  config:
    required: false
  label: Heading
- name: body
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Body
- name: banner
  type: field_group
  config: {}
  fields:
  - name: heading
    type: text
    config:
      required: false
    label: Heading
  label: Banner
- name: faq
  type: field_group_list
  fields:
  - name: question
    type: text
    config:
      required: false
    label: Question
  - name: answer
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: markdown
    label: Answer
  config:
    min: 
    max: 
    labelField: 
  label: FAQ
- name: search_engine_optimization
  type: field_group
  config: {}
  fields:
  - name: seo
    type: include
    config: {}
    template: seo
    label: SEO
  label: Search Engine Optimization
